#pragma once

// I SHOULD APPROACH THIS PART VERY CAREFULLY. I WANT THIS PART OF CODE
// TO BE WRITTEN WELL. I SHOULD PROBABLY DO SOME STRUCT THAT COMBINES:
// - SHADER
// - DATA BUFFER
// - ADDITIONAL VARIABLES
// - HAS SETUP, RUN, AND MAYBE DELETE FUNCTIONS BASED ON TYPE

// typedef enum {
// } DataBufferType;